name: hello-world
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello_world
        run: echo "hello world!"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: good_bye
        run: echo "good bye!"
        shell: bash
    
    
    
    
      
